import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Message from "../components/Message";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Creative Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-12 text-lg font-medium">
          <h2>See what other people are saying</h2>
        </div>
      </main>
    </>
  );
}
